### ISSUE TITLE
getPrivacyMasks is not a function

### ISSUE THREAD

**Issue by enzo-billis** [scryptedapp/scripts.scrypted.app#9]
Hello
I'm trying to use the script https://github.com/scryptedapp/scripts.scrypted.app/blob/main/privacy-mask-toggle.md
But I have two issues:
- The camera list (on settings drawer) still empty even if I have 2 cameras configured
- When I hard code the IDs, I have an error: device.getPrivacyMasks is not a function
I've logged the device and the device seems fully returned !

**Comment by koush** [comment]
arlo does not support privacy masks

**Comment by enzo-billis** [comment]
Where did I said that I have Arlo cameras ? I have Imou cameras. You told me on Discord to use privacyMode instead. For those having the same needs: Indeed it's working much better to enable/disable nvr detection

**Comment by koush** [comment]
not sure probably had wire crossed
